@host = http://localhost:3005

########################### login

# @name login

POST {{host}}/auth/login
Content-Type: application/json

{
  //"email": "superAdmin@Amer.com",
  "email": "mostafa.ahmed@acapitalholding.com",
  "password": "mostafa@222"
}

####################
@authorization = Bearer {{login.response.body.result.access_token}}

#################### reset password
POST {{host}}/auth/reset-password
Content-Type: application/json
Authorization: {{authorization}}

{
  "employee_id": "daef4ddb-aa8a-4332-af1e-0f1c0a737f36"
}

#################### change password
POST {{host}}/auth/change-password
Content-Type: application/json
Authorization: {{authorization}}

{
  "oldPassword": "mostafa@222",
  "newPassword": "mostafa@333",
  "confirmPassword": "mostafa@333"
}
