@host = http://localhost:3005

########################### login

# @name login

POST {{host}}/auth/login 
Content-Type: application/json

{
  "email": "superAdmin@Amer.com",
  //"email": "mostafa.ahmedd@acapitalholding.com",
  //"password": "C72L0nes"
  "password": "mostafa@222"
}

####################

@authorization = Bearer {{login.response.body.result.access_token}}

########################### create new menu

POST {{host}}/definitions/create-menu
Content-Type: application/json
Authorization: {{authorization}}

{
  "menus": [
    { "en_name": "Dashboard", "ar_name": "لوحة التحكم" },
    { "en_name": "ppm", "ar_name": "الصيانة الوقائية" },
    { "en_name": "Definition", "ar_name": "التعريفات" },
    { "en_name": "Asset", "ar_name": "الأصول" },
    { "en_name": "MaintenancePlan", "ar_name": "خطة الصيانة" },
    { "en_name": "HouseKeeping", "ar_name": "التنظيف" },
    { "en_name": "Unit", "ar_name": "الوحدة" },
    { "en_name": "Services", "ar_name": "الخدمات" },
    { "en_name": "CRM", "ar_name": "إدارة علاقات العملاء" },
    { "en_name": "Customers", "ar_name": "العملاء" },
    { "en_name": "DocumentLibrary", "ar_name": "مكتبة المستندات" },
    { "en_name": "News", "ar_name": "الأخبار" },
    { "en_name": "Ads", "ar_name": "الإعلانات" },
    { "en_name": "Rental", "ar_name": "التأجير" },
    { "en_name": "Annual Maintenance Transactions", "ar_name": "المعاملات السنوية للصيانة" },
    { "en_name": "Tickets", "ar_name": "التذاكر" },
    { "en_name": "Inquiries", "ar_name": "الاستفسارات" },
    { "en_name": "Complains", "ar_name": "الشكاوى" },
    { "en_name": "Invoices", "ar_name": "الفواتير" },
    { "en_name": "Contract", "ar_name": "العقود" },
    { "en_name": "Mobile Services", "ar_name": "الخدمات المحمولة" },
    { "en_name": "Reports", "ar_name": "التقارير" },
    { "en_name": "Security", "ar_name": "الأمان" },
    { "en_name": "Users", "ar_name": "المستخدمين" },
    { "en_name": "Roles", "ar_name": "الأدوار" },
    { "en_name": "Settings", "ar_name": "الاعدادات" }
  ]
}
########################### create new module

POST {{host}}/definitions/create-menuItems
Content-Type: application/json
Authorization: {{authorization}}

{
  "menuItems": [
    { "menu_id": 1, "en_name": "Dashboard", "ar_name": "لوحة التحكم" },

    { "menu_id": 3, "en_name": "Client", "ar_name": "العميل" },
    { "menu_id": 3, "en_name": "Area", "ar_name": "المنطقة" },
    { "menu_id": 3, "en_name": "Positions", "ar_name": "الموظفين" },
    { "menu_id": 3, "en_name": "Safe", "ar_name": "الخزانة" },
    { "menu_id": 3, "en_name": "Project", "ar_name": "المشروع" },
    { "menu_id": 3, "en_name": "Location Type", "ar_name": "نوع الموقع" },
    { "menu_id": 3, "en_name": "Department", "ar_name": "القسم" },
    { "menu_id": 3, "en_name": "Category", "ar_name": "الفئة" },
    { "menu_id": 3, "en_name": "Brand", "ar_name": "العلامة التجارية" },
    { "menu_id": 3, "en_name": "Model", "ar_name": "الموديل" },
    { "menu_id": 3, "en_name": "Location", "ar_name": "الموقع" },
    { "menu_id": 3, "en_name": "Employee", "ar_name": "الموظف" },
    { "menu_id": 3, "en_name": "Maintenance Plan Type", "ar_name": "نوع خطة الصيانة" },
    { "menu_id": 3, "en_name": "Tax", "ar_name": "الضريبة" },
    { "menu_id": 3, "en_name": "Contract Type", "ar_name": "نوع العقد" },
    { "menu_id": 3, "en_name": "Sister Companies", "ar_name": "الشركات الشقيقة" },
    { "menu_id": 3, "en_name": "Invoice Types", "ar_name": "أنواع الفواتير" },
    { "menu_id": 3, "en_name": "Complain Classifications", "ar_name": "تصنيفات الشكاوى" },
    { "menu_id": 3, "en_name": "Transaction Type Groups", "ar_name": "مجموعات أنواع المعاملات" },
    { "menu_id": 3, "en_name": "Transaction Types", "ar_name": "أنواع المعاملات" },
    { "menu_id": 3, "en_name": "Service Provider Companies", "ar_name": "شركات مزودي الخدمة" },
    { "menu_id": 3, "en_name": "Bank-Keys", "ar_name": "مفاتيح البنوك" },
    { "menu_id": 3, "en_name": "Service Categories", "ar_name": "فئات الخدمات" },
    { "menu_id": 3, "en_name": "Rental Companies", "ar_name": "شركات التأجير" },
    { "menu_id": 3, "en_name": "Zones", "ar_name": "المناطق" },

    { "menu_id": 4, "en_name": "Search Assets", "ar_name": "بحث الأصول" },
    { "menu_id": 4, "en_name": "Add Asset", "ar_name": "إضافة أصل" },

    { "menu_id": 5, "en_name": "Maintenance Plan Type", "ar_name": "نوع خطة الصيانة" },
    { "menu_id": 5, "en_name": "Review", "ar_name": "مراجعة" },
    { "menu_id": 5, "en_name": "Create MP", "ar_name": "إنشاء خطة صيانة" },
    { "menu_id": 5, "en_name": "Search MP", "ar_name": "بحث خطة صيانة" },
    { "menu_id": 5, "en_name": "MP Assign Employee", "ar_name": "تعيين موظف" },
    { "menu_id": 5, "en_name": "MP Calendar", "ar_name": "تقويم خطة الصيانة" },
    { "menu_id": 5, "en_name": "Corrective MP", "ar_name": "خطة صيانة تصحيحية" },
    { "menu_id": 5, "en_name": "Daily Tasks", "ar_name": "المهام اليومية" },
    { "menu_id": 5, "en_name": "Print Daily Tasks", "ar_name": "طباعة المهام اليومية" },

    { "menu_id": 6, "en_name": "HouseKeeping Types", "ar_name": "أنواع التنظيف" },
    { "menu_id": 6, "en_name": "Create", "ar_name": "إنشاء" },
    { "menu_id": 6, "en_name": "Search", "ar_name": "بحث" },
    { "menu_id": 6, "en_name": "Assign Employee", "ar_name": "تعيين موظف" },
    { "menu_id": 6, "en_name": "Calendar", "ar_name": "التقويم" },
    { "menu_id": 6, "en_name": "Daily Tasks", "ar_name": "المهام اليومية" },
    { "menu_id": 6, "en_name": "Review", "ar_name": "مراجعة" },
    { "menu_id": 6, "en_name": "Print Daily Tasks", "ar_name": "طباعة المهام اليومية" },

    { "menu_id": 7, "en_name": "Search Unit", "ar_name": "بحث وحدة" },

    { "menu_id": 8, "en_name": "Service Search", "ar_name": "بحث خدمة" },
    { "menu_id": 8, "en_name": "Add Service", "ar_name": "إضافة خدمة" },

    { "menu_id": 9, "en_name": "CRM", "ar_name": "إدارة علاقات العملاء" },

    { "menu_id": 10, "en_name": "Search Customer", "ar_name": "بحث عميل" },

    { "menu_id": 11, "en_name": "Document Library", "ar_name": "مكتبة المستندات" },

    { "menu_id": 12, "en_name": "News", "ar_name": "الأخبار" },

    { "menu_id": 13, "en_name": "Ads", "ar_name": "الإعلانات" },

    { "menu_id": 14, "en_name": "Add Rental File", "ar_name": "إضافة ملف تأجير" },
    { "menu_id": 14, "en_name": "All Files", "ar_name": "كل الملفات" },

    { "menu_id": 15, "en_name": "Annual Maintenece", "ar_name": "الصيانة السنوية" },
    { "menu_id": 15, "en_name": "Add a Transaction", "ar_name": "إضافة معاملة" },
    { "menu_id": 15, "en_name": "Reports", "ar_name": "التقارير" },

    { "menu_id": 16, "en_name": "Add Ticket", "ar_name": "إضافة تذكرة" },
    { "menu_id": 16, "en_name": "Search Tickets", "ar_name": "بحث التذاكر" },
    { "menu_id": 16, "en_name": "Ticket", "ar_name": "تذكرة" },
    { "menu_id": 16, "en_name": "Add Ticket", "ar_name": "إضافة تذكرة" },
    { "menu_id": 16, "en_name": "Search Tickets", "ar_name": "بحث التذاكر" },
    { "menu_id": 16, "en_name": "All Tickets", "ar_name": "كل التذاكر" },
    { "menu_id": 16, "en_name": "Mobile Request", "ar_name": "طلب عبر الهاتف" },
    { "menu_id": 16, "en_name": "Under Process", "ar_name": "قيد التنفيذ" },
    { "menu_id": 16, "en_name": "CTS", "ar_name": "نظام CTS" },
    { "menu_id": 16, "en_name": "History", "ar_name": "السجل" },

    { "menu_id": 17, "en_name": "Search Inquiry", "ar_name": "بحث استفسار" },
    { "menu_id": 17, "en_name": "Add Inquiry", "ar_name": "إضافة استفسار" },

    { "menu_id": 18, "en_name": "Add Complain", "ar_name": "إضافة شكوى" },

    { "menu_id": 19, "en_name": "Invoices", "ar_name": "الفواتير" },
    { "menu_id": 19, "en_name": "Create", "ar_name": "إنشاء" },
    { "menu_id": 19, "en_name": "Pending Invoices", "ar_name": "الفواتير المعلقة" },
    { "menu_id": 19, "en_name": "Search Invoices", "ar_name": "بحث الفواتير" },
    { "menu_id": 19, "en_name": "All Invoices", "ar_name": "كل الفواتير" },
    { "menu_id": 19, "en_name": "Void Requests", "ar_name": "طلبات الإلغاء" },
    { "menu_id": 19, "en_name": "End Of Day", "ar_name": "نهاية اليوم" },
    { "menu_id": 19, "en_name": "Full End Of Day", "ar_name": "نهاية اليوم الكاملة" },

    { "menu_id": 20, "en_name": "Contract", "ar_name": "العقد" },
    { "menu_id": 20, "en_name": "Search Contracts", "ar_name": "بحث العقود" },
    { "menu_id": 20, "en_name": "Create Contract", "ar_name": "إنشاء عقد" },
    { "menu_id": 20, "en_name": "Reschedual Approvals", "ar_name": "موافقات إعادة الجدولة" },
    { "menu_id": 20, "en_name": "Search Requests", "ar_name": "بحث الطلبات" },
    { "menu_id": 20, "en_name": "Payment List", "ar_name": "قائمة المدفوعات" },

    { "menu_id": 21, "en_name": "Mobile Services", "ar_name": "الخدمات المحمولة" },
    { "menu_id": 21, "en_name": "Notification Center", "ar_name": "مركز الإشعارات" },
    { "menu_id": 21, "en_name": "Notification Log", "ar_name": "سجل الإشعارات" },
    { "menu_id": 21, "en_name": "Visits", "ar_name": "الزيارات" },

    { "menu_id": 22, "en_name": "Reports", "ar_name": "التقارير" },
    { "menu_id": 22, "en_name": "Online Payments", "ar_name": "المدفوعات الإلكترونية" },
    { "menu_id": 22, "en_name": "Daily Invoices", "ar_name": "الفواتير اليومية" },
    { "menu_id": 22, "en_name": "Grouped Daily Invoices", "ar_name": "الفواتير اليومية المجمعة" },
    { "menu_id": 22, "en_name": "End Of Day", "ar_name": "نهاية اليوم" },
    { "menu_id": 22, "en_name": "Detailed Daily Invoices", "ar_name": "الفواتير اليومية التفصيلية" },
    { "menu_id": 22, "en_name": "Sap Invoices Report", "ar_name": "تقرير فواتير SAP" },
    { "menu_id": 22, "en_name": "Voids", "ar_name": "الفواتير الملغاة" },
    { "menu_id": 22, "en_name": "Department Service End Of Day Report", "ar_name": "تقرير نهاية اليوم لخدمات الأقسام" },
    { "menu_id": 22, "en_name": "Current Work Orders", "ar_name": "أوامر العمل الحالية" },
    { "menu_id": 22, "en_name": "System Logs", "ar_name": "سجلات النظام" },
    { "menu_id": 22, "en_name": "Deprecated Assets", "ar_name": "الأصول المهملة" },
    { "menu_id": 22, "en_name": "Delayed Tickets", "ar_name": "التذاكر المتأخرة" },

    { "menu_id": 23, "en_name": "Security", "ar_name": "الأمان" },

    { "menu_id": 24, "en_name": "Users", "ar_name": "المستخدمين" },
    { "menu_id": 24, "en_name": "Manage Users", "ar_name": "إدارة المستخدمين" },
    { "menu_id": 24, "en_name": "Add User", "ar_name": "إضافة مستخدم" },
    { "menu_id": 24, "en_name": "Pending Requests", "ar_name": "الطلبات المعلقة" },

    { "menu_id": 25, "en_name": "Roles", "ar_name": "الأدوار" },
    { "menu_id": 25, "en_name": "Manage Roles", "ar_name": "إدارة الأدوار" },
    { "menu_id": 25, "en_name": "Add Role", "ar_name": "إضافة دور" },

    { "menu_id": 26, "en_name": "System Settings", "ar_name": "إعدادات النظام" },
    { "menu_id": 26, "en_name": "System Configuration", "ar_name": "إعدادات النظام" },
    { "menu_id": 26, "en_name": "Explicit System Configuration", "ar_name": "إعدادات النظام التفصيلية" },
    { "menu_id": 26, "en_name": "Attendance", "ar_name": "الحضور" },
    { "menu_id": 26, "en_name": "Mobile Error Logs", "ar_name": "سجلات أخطاء الهاتف المحمول" }
  ]
}

########################### create new feature

POST {{host}}/definitions/create-privilege
Content-Type: application/json
Authorization: {{authorization}}

{
  "privilegeItems": [
    {"en_name": "Add", "ar_name": "إضافة"},
    {"en_name": "Add Emergency MP", "ar_name": "إضافة طوارئ MP"},
    {"en_name": "Assign Employee", "ar_name": "تعيين موظف"},
    {"en_name": "Assign Ownership", "ar_name": "تعيين الملكية"},
    {"en_name": "Cancel", "ar_name": "إلغاء"},
    {"en_name": "Chat", "ar_name": "دردشة"},
    {"en_name": "Collect Invoice", "ar_name": "تحصيل فاتورة"},
    {"en_name": "Confirm", "ar_name": "تأكيد"},
    {"en_name": "Current Work Orders", "ar_name": "أوامر العمل الحالية"},
    {"en_name": "Daily Invoices", "ar_name": "الفواتير اليومية"},
    {"en_name": "Daily Tasks", "ar_name": "المهام اليومية"},
    {"en_name": "Delayed Tickets", "ar_name": "التذاكر المتأخرة"},
    {"en_name": "Delete", "ar_name": "حذف"},
    {"en_name": "Department / Service End of day", "ar_name": "القسم / الخدمة نهاية اليوم"},
    {"en_name": "Deprecated Assets", "ar_name": "الأصول المهملة"},
    {"en_name": "Detailed Daily Invoices", "ar_name": "الفواتير اليومية المفصلة"},
    {"en_name": "Edit", "ar_name": "تعديل"},
    {"en_name": "Edit Price", "ar_name": "تعديل السعر"},
    {"en_name": "End Of Day", "ar_name": "نهاية اليوم"},
    {"en_name": "Explicit", "ar_name": "صريح"},
    {"en_name": "Export", "ar_name": "تصدير"},
    {"en_name": "Export Data", "ar_name": "تصدير البيانات"},
    {"en_name": "FullEnd Of Day", "ar_name": "نهاية اليوم الكاملة"},
    {"en_name": "Grouped Daily Invoices", "ar_name": "الفواتير اليومية المجمعة"},
    {"en_name": "History", "ar_name": "السجل"},
    {"en_name": "Lock User", "ar_name": "قفل المستخدم"},
    {"en_name": "Mobile Error Logs", "ar_name": "سجلات أخطاء الهاتف"},
    {"en_name": "Mobile users only", "ar_name": "للمستخدمين عبر الهاتف فقط"},
    {"en_name": "Modify Unit Rent Eligibility", "ar_name": "تعديل أهلية إيجار الوحدة"},
    {"en_name": "Notification Center", "ar_name": "مركز الإشعارات"},
    {"en_name": "Online Payments Report", "ar_name": "تقرير المدفوعات عبر الإنترنت"},
    {"en_name": "Pending Requests", "ar_name": "الطلبات المعلقة"},
    {"en_name": "Pending Tickets", "ar_name": "التذاكر المعلقة"},
    {"en_name": "Read", "ar_name": "قراءة"},
    {"en_name": "Read All", "ar_name": "قراءة الكل"},
    {"en_name": "Reschedule Approval", "ar_name": "إعادة جدولة الموافقة"},
    {"en_name": "Reschedule Approval Without Limits", "ar_name": "إعادة جدولة الموافقة بدون حدود"},
    {"en_name": "Reset Password", "ar_name": "إعادة تعيين كلمة المرور"},
    {"en_name": "Respond", "ar_name": "رد"},
    {"en_name": "Review", "ar_name": "مراجعة"},
    {"en_name": "Search All Requests", "ar_name": "بحث في جميع الطلبات"},
    {"en_name": "Search Requests", "ar_name": "بحث في الطلبات"},
    {"en_name": "Show Calendar", "ar_name": "عرض التقويم"},
    {"en_name": "System Configuration", "ar_name": "إعدادات النظام"},
    {"en_name": "System Logs", "ar_name": "سجلات النظام"},
    {"en_name": "User Projects", "ar_name": "مشاريع المستخدم"},
    {"en_name": "User Requests", "ar_name": "طلبات المستخدم"},
    {"en_name": "Visits", "ar_name": "الزيارات"},
    {"en_name": "Void", "ar_name": "إلغاء"},
    {"en_name": "Void Requests", "ar_name": "إلغاء الطلبات"},
    {"en_name": "Voids", "ar_name": "الإلغاءات"}
  ]
}

########################### get features

GET {{host}}/definitions/get-privileges?lang=en&privilegeName=customer
# GET {{host}}/definitions/get-features?lang=en&moduleName=d
Content-Type: application/json
Authorization: {{authorization}}

{

}

########################### update or assign feature to module


POST {{host}}/definitions/assign-privilege-to-menuItem
Content-Type: application/json
Authorization: {{authorization}}

{
  "privileges": [
    { "menuItem_id": 2, "privilege_id": 1 },   
    { "menuItem_id": 3, "privilege_id": 1 },   
    { "menuItem_id": 6, "privilege_id": 1 },   
    { "menuItem_id": 12, "privilege_id": 1 },  
    { "menuItem_id": 50, "privilege_id": 1 },  
    { "menuItem_id": 8, "privilege_id": 1 },   
    { "menuItem_id": 9, "privilege_id": 1 },   
    { "menuItem_id": 10, "privilege_id": 1 },  
    { "menuItem_id": 11, "privilege_id": 1 },  
    { "menuItem_id": 7, "privilege_id": 1 },   
    { "menuItem_id": 13, "privilege_id": 1 },  
    { "menuItem_id": 14, "privilege_id": 1 },  
    { "menuItem_id": 28, "privilege_id": 1 },  
    { "menuItem_id": 46, "privilege_id": 1 },  
    { "menuItem_id": 48, "privilege_id": 1 },  
    { "menuItem_id": 31, "privilege_id": 1 },  
    { "menuItem_id": 106, "privilege_id": 1 }, 
    { "menuItem_id": 110, "privilege_id": 1 }, 
    { "menuItem_id": 59, "privilege_id": 1 },  
    { "menuItem_id": 15, "privilege_id": 1 },  
    { "menuItem_id": 80, "privilege_id": 1 },  
    { "menuItem_id": 112, "privilege_id": 1 }, 
    { "menuItem_id": 72, "privilege_id": 1 },  
    { "menuItem_id": 38, "privilege_id": 1 },  
    { "menuItem_id": 43, "privilege_id": 1 },  
    { "menuItem_id": 5, "privilege_id": 1 },   
    { "menuItem_id": 114, "privilege_id": 1 }, 
    { "menuItem_id": 4, "privilege_id": 1 },   
    { "menuItem_id": 17, "privilege_id": 1 },  
    { "menuItem_id": 18, "privilege_id": 1 },  
    { "menuItem_id": 67, "privilege_id": 1 },  
    { "menuItem_id": 19, "privilege_id": 1 },  
    { "menuItem_id": 71, "privilege_id": 1 },  
    { "menuItem_id": 69, "privilege_id": 1 },  
    { "menuItem_id": 52, "privilege_id": 1 },  
    { "menuItem_id": 53, "privilege_id": 1 },  
    { "menuItem_id": 56, "privilege_id": 1 },  
    { "menuItem_id": 22, "privilege_id": 1 }, 
    { "menuItem_id": 23, "privilege_id": 1 }, 
    { "menuItem_id": 24, "privilege_id": 1 }, 
    { "menuItem_id": 25, "privilege_id": 1 }, 
    { "menuItem_id": 26, "privilege_id": 1 }, 
    { "menuItem_id": 86, "privilege_id": 2 },  
    { "menuItem_id": 31, "privilege_id": 2 }, 
    { "menuItem_id": 104, "privilege_id": 28 },
    { "menuItem_id": 31, "privilege_id": 3 }, 
    { "menuItem_id": 43, "privilege_id": 3 }, 
    { "menuItem_id": 46, "privilege_id": 3 }, 
    { "menuItem_id": 43, "privilege_id": 5 }, 
    { "menuItem_id": 31, "privilege_id": 5 },  
    { "menuItem_id": 50, "privilege_id": 6 },  
    { "menuItem_id": 72, "privilege_id": 7 },  
    { "menuItem_id": 43, "privilege_id": 8 },  
    { "menuItem_id": 58, "privilege_id": 10 }, 
    { "menuItem_id": 43, "privilege_id": 11 }, 
    { "menuItem_id": 31, "privilege_id": 11 }, 
    { "menuItem_id": 58, "privilege_id": 12 }, 
    { "menuItem_id": 5, "privilege_id": 13 },  
    { "menuItem_id": 18, "privilege_id": 13 }, 
    { "menuItem_id": 17, "privilege_id": 13 }, 
    { "menuItem_id": 22, "privilege_id": 13 }, 
    { "menuItem_id": 23, "privilege_id": 13 }, 
    { "menuItem_id": 51, "privilege_id": 13 }, 
    { "menuItem_id": 19, "privilege_id": 13 },
    { "menuItem_id": 26, "privilege_id": 13 }, 
    { "menuItem_id": 25, "privilege_id": 13 }, 
    { "menuItem_id": 24, "privilege_id": 13 }, 
    { "menuItem_id": 104, "privilege_id": 13 },
    { "menuItem_id": 110, "privilege_id": 13 },
    { "menuItem_id": 15, "privilege_id": 13 }, 
    { "menuItem_id": 61, "privilege_id": 13 }, 
    { "menuItem_id": 43, "privilege_id": 13 }, 
    { "menuItem_id": 38, "privilege_id": 13 }, 
    { "menuItem_id": 72, "privilege_id": 13 }, 
    { "menuItem_id": 112, "privilege_id": 13 },
    { "menuItem_id": 80, "privilege_id": 13 }, 
    { "menuItem_id": 46, "privilege_id": 13 }, 
    { "menuItem_id": 28, "privilege_id": 13 }, 
    { "menuItem_id": 31, "privilege_id": 13 }, 
    { "menuItem_id": 48, "privilege_id": 13 }, 
    { "menuItem_id": 14, "privilege_id": 13 }, 
    { "menuItem_id": 13, "privilege_id": 13 },
    { "menuItem_id": 7, "privilege_id": 13 },    
    { "menuItem_id": 11, "privilege_id": 13 },   
    { "menuItem_id": 10, "privilege_id": 13 },   
    { "menuItem_id": 9, "privilege_id": 13 },    
    { "menuItem_id": 8, "privilege_id": 13 },    
    { "menuItem_id": 12, "privilege_id": 13 },   
    { "menuItem_id": 3, "privilege_id": 13 },    
    { "menuItem_id": 6, "privilege_id": 13 },    
    { "menuItem_id": 50, "privilege_id": 13 },   
    { "menuItem_id": 2, "privilege_id": 13 },   
    { "menuItem_id": 98, "privilege_id": 14 },  
    { "menuItem_id": 101, "privilege_id": 15 }, 
    { "menuItem_id": 95, "privilege_id": 16 },  
    { "menuItem_id": 5, "privilege_id": 17 },   
    { "menuItem_id": 4, "privilege_id": 17 },   
    { "menuItem_id": 17, "privilege_id": 17 },  
    { "menuItem_id": 18, "privilege_id": 17 },  
    { "menuItem_id": 19, "privilege_id": 17 },  
    { "menuItem_id": 67, "privilege_id": 17 },  
    { "menuItem_id": 69, "privilege_id": 17 },  
    { "menuItem_id": 52, "privilege_id": 17 },  
    { "menuItem_id": 53, "privilege_id": 17 },  
    { "menuItem_id": 22, "privilege_id": 17 },  
    { "menuItem_id": 23, "privilege_id": 17 },  
    { "menuItem_id": 24, "privilege_id": 17 },  
    { "menuItem_id": 25, "privilege_id": 17 },  
    { "menuItem_id": 26, "privilege_id": 17 },  
    { "menuItem_id": 2, "privilege_id": 17 },   
    { "menuItem_id": 3, "privilege_id": 17 },   
    { "menuItem_id": 50, "privilege_id": 17 },  
    { "menuItem_id": 12, "privilege_id": 17 },  
    { "menuItem_id": 6, "privilege_id": 17 },   
    { "menuItem_id": 8, "privilege_id": 17 },   
    { "menuItem_id": 9, "privilege_id": 17 },   
    { "menuItem_id": 10, "privilege_id": 17 },  
    { "menuItem_id": 11, "privilege_id": 17 },  
    { "menuItem_id": 7, "privilege_id": 17 },   
    { "menuItem_id": 13, "privilege_id": 17 },  
    { "menuItem_id": 14, "privilege_id": 17 },  
    { "menuItem_id": 48, "privilege_id": 17 },  
    { "menuItem_id": 31, "privilege_id": 17 },  
    { "menuItem_id": 28, "privilege_id": 17 },  
    { "menuItem_id": 46, "privilege_id": 17 },  
    { "menuItem_id": 112, "privilege_id": 17 }, 
    { "menuItem_id": 72, "privilege_id": 17 },  
    { "menuItem_id": 38, "privilege_id": 17 },  
    { "menuItem_id": 43, "privilege_id": 17 },  
    { "menuItem_id": 15, "privilege_id": 17 },   
    { "menuItem_id": 80, "privilege_id": 17 },   
    { "menuItem_id": 110, "privilege_id": 17 },  
    { "menuItem_id": 61, "privilege_id": 17 },   
    { "menuItem_id": 104, "privilege_id": 17 },
    { "menuItem_id": 47, "privilege_id": 17 }, 
    { "menuItem_id": 61, "privilege_id": 18 },  
    { "menuItem_id": 72, "privilege_id": 19 },  
    { "menuItem_id": 58, "privilege_id": 19 },  
    { "menuItem_id": 111, "privilege_id": 20 }, 
    { "menuItem_id": 43, "privilege_id": 21 },  
    { "menuItem_id": 46, "privilege_id": 21 },  
    { "menuItem_id": 28, "privilege_id": 21 }, 
    { "menuItem_id": 48, "privilege_id": 21 }, 
    { "menuItem_id": 50, "privilege_id": 21 }, 
    { "menuItem_id": 72, "privilege_id": 23 }, 
    { "menuItem_id": 58, "privilege_id": 24 },  
    { "menuItem_id": 61, "privilege_id": 25 }, 
    { "menuItem_id": 104, "privilege_id": 26 },
    { "menuItem_id": 115, "privilege_id": 27 }, 
    { "menuItem_id": 46, "privilege_id": 29 },  
    { "menuItem_id": 87, "privilege_id": 30 },  
    { "menuItem_id": 91, "privilege_id": 31 },  
    { "menuItem_id": 107, "privilege_id": 32 },
    { "menuItem_id": 61, "privilege_id": 33 }, 
    { "menuItem_id": 61, "privilege_id": 34 },  
    { "menuItem_id": 15, "privilege_id": 34 },  
    { "menuItem_id": 80, "privilege_id": 34 },  
    { "menuItem_id": 110, "privilege_id": 34 }, 
    { "menuItem_id": 104, "privilege_id": 34 }, 
    { "menuItem_id": 72, "privilege_id": 34 },  
    { "menuItem_id": 112, "privilege_id": 34 }, 
    { "menuItem_id": 43, "privilege_id": 34 },  
    { "menuItem_id": 38, "privilege_id": 34 },  
    { "menuItem_id": 46, "privilege_id": 34 },  
    { "menuItem_id": 48, "privilege_id": 34 },  
    { "menuItem_id": 31, "privilege_id": 34 },  
    { "menuItem_id": 28, "privilege_id": 34 },  
    { "menuItem_id": 14, "privilege_id": 34 },  
    { "menuItem_id": 13, "privilege_id": 34 },  
    { "menuItem_id": 7, "privilege_id": 34 },   
    { "menuItem_id": 8, "privilege_id": 34 },   
    { "menuItem_id": 9, "privilege_id": 34 },   
    { "menuItem_id": 11, "privilege_id": 34 },  
    { "menuItem_id": 10, "privilege_id": 34 },  
    { "menuItem_id": 12, "privilege_id": 34 },  
    { "menuItem_id": 50, "privilege_id": 34 },  
    { "menuItem_id": 6, "privilege_id": 34 },  
    { "menuItem_id": 3, "privilege_id": 34 },  
    { "menuItem_id": 2, "privilege_id": 34 },  
    { "menuItem_id": 115, "privilege_id": 34 },
    { "menuItem_id": 5, "privilege_id": 34 },  
    { "menuItem_id": 4, "privilege_id": 34 },  
    { "menuItem_id": 18, "privilege_id": 34 }, 
    { "menuItem_id": 17, "privilege_id": 34 }, 
    { "menuItem_id": 47, "privilege_id": 34 }, 
    { "menuItem_id": 53, "privilege_id": 34 }, 
    { "menuItem_id": 56, "privilege_id": 34 },  
    { "menuItem_id": 69, "privilege_id": 34 }, 
    { "menuItem_id": 52, "privilege_id": 34 }, 
    { "menuItem_id": 1, "privilege_id": 34 },  
    { "menuItem_id": 71, "privilege_id": 34 }, 
    { "menuItem_id": 67, "privilege_id": 34 }, 
    { "menuItem_id": 51, "privilege_id": 34 }, 
    { "menuItem_id": 19, "privilege_id": 34 },  
    { "menuItem_id": 25, "privilege_id": 34 }, 
    { "menuItem_id": 26, "privilege_id": 34 }, 
    { "menuItem_id": 72, "privilege_id": 35 }, 
    { "menuItem_id": 61, "privilege_id": 35 }, 
    { "menuItem_id": 83, "privilege_id": 36 },  
    { "menuItem_id": 83, "privilege_id": 37 },  
    { "menuItem_id": 104, "privilege_id": 38 },
    { "menuItem_id": 71, "privilege_id": 39 }, 
    { "menuItem_id": 31, "privilege_id": 40 }, 
    { "menuItem_id": 43, "privilege_id": 40 }, 
    { "menuItem_id": 83, "privilege_id": 41 },  
    { "menuItem_id": 83, "privilege_id": 42 },  
    { "menuItem_id": 99, "privilege_id": 9 },   
    { "menuItem_id": 43, "privilege_id": 43 },  
    { "menuItem_id": 31, "privilege_id": 43 }, 
    { "menuItem_id": 111, "privilege_id": 44 }, 
    { "menuItem_id": 100, "privilege_id": 45 },
    { "menuItem_id": 104, "privilege_id": 46 },
    { "menuItem_id": 104, "privilege_id": 47 },
    { "menuItem_id": 86, "privilege_id": 48 }, 
    { "menuItem_id": 72, "privilege_id": 49 }, 
    { "menuItem_id": 77, "privilege_id": 50 }, 
    { "menuItem_id": 97, "privilege_id": 51 },
    { "menuItem_id": 72, "privilege_id": 49 },
    { "menuItem_id": 77, "privilege_id": 50 }, 
    { "menuItem_id": 97, "privilege_id": 51 } ]

}

############################# create new department

POST {{host}}/definitions/department
Content-Type: application/json
Authorization: {{authorization}}

{
  "en_name": "Accounting",
  "ar_name": "الحسابات"
  //,"show_in_mobile": 1
}


############################# create service config

POST {{host}}/definitions/service-config
Content-Type: application/json
Authorization: {{authorization}}

{
  //"technical_staff_count": 4, 
  //"SLA": "60m",
  //"delay": "60m",
  //"is_active": 1,
  //"project_id": 3
}

################## get service configs
GET {{host}}/definitions/service-configs
Content-Type: application/json
Authorization: {{authorization}} 

############################## create new service

POST {{host}}/definitions/service
Content-Type: application/json
Authorization: {{authorization}}

{
  "en_name": "deep cleaning",
  "ar_name": "تنظيف عميق",
  "description": "this is deep cleaning service",
  "department_id": 1,
  "service_config_id": 1,
  "price": 0,
  //"is_active": 1,
  //"show_in_mobile": 1,
  //"en_mobile_service_name": "deep cleaning",
  //"ar_mobile_service_name": "تنظيف عميق",
  //"start_date": "2023-01-01"
}

############################## get services
GET {{host}}/definitions/services?page=1&limit=1
Content-Type: application/json
Authorization: {{authorization}}

############################## get all dropdown
GET {{host}}/definitions/all-dropdowns
Content-Type: application/json
Authorization: {{authorization}}
lang:en


############################### create project safe
POST {{host}}/definitions/safes
Content-Type: application/json
Authorization: {{authorization}}

{
  "en_name": "porto matrouh safe",
  "ar_name": "خزينة بورتو مطروح",
  "project_id": 2
}

############################ create usertypes 
POST {{host}}/definitions/user-types
Content-Type: application/json
Authorization: {{authorization}}

{
  "userTypes": [
    { "en_name": "Master Account", "ar_name": "حساب رئيسي", "project_id": 1 },
    { "en_name": "HOD", "ar_name": "رئيس قسم", "project_id": 1 },
    { "en_name": "Dispatcher", "ar_name": "الموزع", "project_id": 1 },
    { "en_name": "Technician", "ar_name": "الفني", "project_id": 1 },
    { "en_name": "Agent", "ar_name": "الوكيل", "project_id": 1 }
  ]
}

############################# create positions
POST {{host}}/definitions/positions
Content-Type: application/json
Authorization: {{authorization}}

{
  "positions": [
    { "en_name": "General Manager", "ar_name": "المدير العام", "project_id": 2 },
    { "en_name": "HR Manager", "ar_name": "مدير الموارد البشرية", "project_id": 2 },
    { "en_name": "Finance Manager", "ar_name": "مدير المالية", "project_id": 2 },
    { "en_name": "Sales Manager", "ar_name": "مدير المبيعات", "project_id": 2 },
    { "en_name": "IT Manager", "ar_name": "مدير تكنولوجيا المعلومات", "project_id": 2 }
  ]
}