export const superAdminEnums = {
  EMAIL: "superAdmin@Amer.com",
  USER_NAME: "superAdmin",
  FULL_NAME: "Super Admin",
  PHONE_NUMBER: "01124284915",
  PASSWORD: "mostafa@222",
  IS_MALE: 1,
  ROLE_EN_NAME: "Super Admin",
  ROLE_AR_NAME: "المدير العام",
  DEPARTMENT_EN_NAME: "Super Admin Department",
  DEPARTMENT_AR_NAME: "قسم المدير العام",
  POSITION_EN_NAME: "Super Admin Position",
  POSITION_AR_NAME: "المدير العام"
}
export const languageEnums = {
  ENGLISH: "en",
  ARABIC: "ar",
};

export const genderEnums = {
  MALE: 1,
  FEMALE: 0,
};

export const projectEnums = {
  ALL_PROJECTS: 1
};

export const isDeleteStatusEnums = {
  DELETED: 1,
  NOT_DELETED: 0,
}

export const activeStatusEnums = {
  ACTIVE: 1,
  INACTIVE: 0,
}

export const mailerEnums = {
  MAILER_SUBJECT: 'Welcome to MyPorto CRM!',
}

export const autogeneratedPasswordEnums = {
  LENGTH: 8,
}

export const safeEnums = {
  DEFAULT_SAFE_EN_NAME: "Cairo Safe",
  DEFAULT_SAFE_AR_NAME: "خزينة القاهرة",
}

export const promiseStatusEnums = {
  FULFILLED: 'fulfilled',
  REJECTED: 'rejected',
}

